/**
 * Created by jplamb on 5/9/17.
 */
import DS from 'ember-data';

const { attr, hasMany } = DS;

export default DS.Model.extend({
	week :	 attr('number'),
	player_id:	 attr('number'),
	game_date:	 attr('date'), //date?
	player_name:	 attr('string'),
	opp:	 attr('string'),
	result:	 attr('string'),
	victory:	 attr('string'),
	completions:	 attr('number'),
	pass_att:	 attr('number'),
	pass_yards:	 attr('number'),
	compl_pct:	 attr('number'),
	pass_long:	 attr('number'),
	pass_td:	 attr('number'),
	int_thrown:	 attr('number'),
	pass_rate:	 attr('number'),
	raw_qbr:	 attr('number'),
	adj_qbr:	 attr('number'),
	rush_att:	 attr('number'),
	rush_yards:	 attr('number'),
	rush_avg:	 attr('number'),
	rush_long:	 attr('number'),
	rush_td:	 attr('number'),
	receptions:	 attr('number'),
	rec_yards:	 attr('number'),
	rec_avg:	 attr('number'),
	rec_long:	 attr('number'),
	rec_td:	 attr('number'),
	fg_1_19:	 attr('number'),
	fg_20_29:	 attr('number'),
	fg_30_39:	 attr('number'),
	fg_40_49:	 attr('number'),
	fg_50_plus:	 attr('number'),
	fg_made:	 attr('number'),
	fg_pct:	 attr('number'),
	fg_long:	 attr('number'),
	xp_made:	 attr('number'),
	xp_att:	 attr('number'),
	kick_points:	 attr('number'),
	def_tot_tack:	 attr('number'),
	def_unassist_tack:	 attr('number'),
	def_assist_tack:	 attr('number'),
	def_sacks:	 attr('number'),
	def_force_fmble:	 attr('number'),
	def_int_ret_yrds:	 attr('number'),
	def_int_ret_avg:	 attr('number'),
	def_int_ret_long:	 attr('number'),
	def_int_ret_td:	 attr('number'),
	def_pass_defend:	 attr('number'),
	punt_total:	 attr('number'),
	punt_avg:	 attr('number'),
	punt_long:	 attr('number'),
	punt_total_yrds:	 attr('number'),
	primary:	 attr('number'),
});
